#!/usr/bin/python3

## set up EVC stuff

import qbroker; qbroker.setup()
import asyncio
import argparse
import uvloop
from twisted.internet import asyncioreactor

loop = uvloop.new_event_loop()
asyncio.set_event_loop(loop)
asyncioreactor.install(eventloop=loop)

from twisted.internet import reactor

import sys
from traceback import print_exc

from devrun.cmd import parser,cmd
from qbroker.util.async import Main

import logging
logger = logging.getLogger(__name__)

class Run(Main):
    def __init__(self,cmd,args, loop=None):
        super().__init__(loop=loop)
        self.cmd = cmd
        self.args = args
    async def at_start(self):
        await self.cmd.start()
        self.job = asyncio.ensure_future(self.cmd.run(*self.args))
        def done(j):
            self.stop()
            try:
                j.result()
            except asyncio.CancelledError:
                pass
            except Exception as exc:
                print_exc()

        self.job.add_done_callback(done)
        self.add_cleanup(self.job.cancel)
        self.add_cleanup(self.cmd.stop)

    def run(self):
        reactor.startRunning(installSignalHandlers=False)
        loop.run_until_complete(self._run())
        if reactor._justStopped:
            reactor._justStopped = False

LOG=[logging.ERROR,logging.WARNING,logging.INFO,logging.DEBUG]

def main():

    p = parser()
    p.add_argument('mode', help='change what to do')
    p.add_argument('args', nargs='*', help='(command-specific)')
    if p.epilog is None: p.epilog = ""
    p.epilog += """\

%(prog)s help           -- list of commands
%(prog)s help ‹command› -- help for this command
"""

    opt = p.parse_args()
    opt.loop = loop
    logging.basicConfig(level=LOG[min(opt.verbose,len(LOG)-1)])
    logging.getLogger('pymodbus').addHandler(logging.NullHandler())
    logging.getLogger('pymodbus').propagate = False

    c = cmd[opt.mode](opt)
    r = Run(c,opt.args, loop=opt.loop)
    try:
        r.run()
    except asyncio.CancelledError:
        pass
    except Exception as exc:
        if opt.verbose > 1:
            raise
        print("%s: %s" % (type(exc).__name__,str(exc)), file=sys.stderr)

if __name__ == '__main__':
    main()
